version: "3.6"

services:
  baseimage:
    build:
      context: ./base-image/
      dockerfile: Dockerfile
    image: "alauda-cloud/java"

  config-server:
    container_name: config-server
    build:
      context: ./config-server/
      dockerfile: Dockerfile
    image: "alauda-cloud/config-server"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - baseimage
    expose:
      - "8001"
    ports:
      - "8001:8080"
    networks:
      - alauda-cloud

  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server/
      dockerfile: Dockerfile
    image: "alauda-cloud/eureka-server"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - baseimage
    expose:
      - "8761"
    ports:
      - "8761:8761"
    networks:
      - alauda-cloud
    depends_on:
      - config-server

networks:
  alauda-cloud:
    name: alauda-cloud
    driver: bridge
